checks:
    php:
        code_rating: true
        duplication: true
tools:
    # use travis code coverage report
    external_code_coverage:
        timeout: 3600
        runs: 1
    # php cs fixer
    php_cs_fixer:
        config: { level: all } 
    # sensiolabs security checker
    sensiolabs_security_checker: true
    # php code sniffer
    php_code_sniffer:
        config:
            standard: "PSR2"
