name: PHPUnit tests
on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    name: On PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Install dependencies (latest)
      run: composer install --prefer-dist --no-progress

    - name: Run test suite (latest)
      run: ./vendor/bin/phpunit

    - name: Install dependencies (lowest)
      run: composer update --prefer-lowest --no-progress

    - name: Run test suite (lowest)
      run: ./vendor/bin/phpunit
